MasterAnnonceLogin {
    org.univ_paris8.iut.montreuil.devav2026.masterannonce.ahuguet.masterannonce.security.module.DbLoginModule required;
};

MasterAnnonceToken {
    org.univ_paris8.iut.montreuil.devav2026.masterannonce.ahuguet.masterannonce.security.module.TokenLoginModule required;
};
